## Original File MIT License Copyright (c) 2024 TinyTakinTeller
class_name MenuButtonEnum

enum ID {
	UNKNOWN,
	MAIN_MENU_PLAY,
	MAIN_MENU_OPTIONS,
	MAIN_MENU_CREDITS,
	MAIN_MENU_QUIT,
	OPTIONS_MENU_BACK,
	OPTIONS_MENU_RESET,
	OPTIONS_MENU_AUDIO_TAB,
	OPTIONS_MENU_VIDEO_TAB,
	OPTIONS_MENU_CONTROLS_TAB,
	OPTIONS_MENU_GAME_TAB,
	CREDITS_MENU_BACK,
	SAVE_FILES_MENU_BACK,
	SAVE_FILES_MENU_PLAY,
	SAVE_FILES_MENU_EXPORT,
	SAVE_FILES_MENU_IMPORT,
	SAVE_FILES_MENU_DELETE,
	SAVE_FILES_MENU_RENAME,
	PAUSE_MENU_CONTINUE,
	PAUSE_MENU_OPTIONS,
	PAUSE_MENU_LEAVE,
	PAUSE_MENU_QUIT,
	GAME_PAUSE,
	GAME_LEAVE
}
